Vagrant.configure("2") do |config|
  # box
  config.vm.box = "ubuntu/jammy64"

  # machine
  config.vm.provider "virtualbox" do |v|
    v.cpus = 4
    v.memory = 8192
  end

  # provision
  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
      apt-get update
      DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
      DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential wget gdb
      sudo -u vagrant git clone https://github.com/meng-xu-cs/cs453-program-analysis-platform.git /home/vagrant/cs453-program-analysis-platform
    SHELL
  end
end
