Vagrant.configure("2") do |config|
  # box
  config.vm.box = "ubuntu/jammy64"

  # machine
  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    v.memory = 8192
  end

  # provision
  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
      apt-get update
      DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
      DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential wget gdb
      wget https://github.com/pwndbg/pwndbg/releases/download/2024.08.29/pwndbg_2024.08.29_amd64.deb -O pwndbg.deb
      dpkg -i pwndbg.deb
    SHELL
  end
end
